version: "3"

services:
    app:
        build: .
        command: yarn start
        ports:
            - "3333:3333"
        volumes:
            - .:/usr/app

    mysql:
        image: mysql:latest
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=docker
            - MYSQL_DATABASE=plathanus
        ports:
            - 3306:3306
