version: "3"

services:
    app:
        build: .

        ports:
            - "3333:3333"
        volumes:
            - .:/usr/app
        command: yarn start

    mysql:
        image: mysql:latest
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_DATABASE: plathanus
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: root
            DB_HOSTNAME: localhost

        ports:
            - 3306:3306
